name: 'Publish NPM - patch'
description: 'Bump patch version, publish to npm, push the tag and commit'
inputs:
  working-directory:
    description: 'Package directory'
    required: false
    default: '.'
  run-tests:
    description: 'Run npm test before publishing'
    required: false
    default: 'false'
  access:
    description: 'npm access flag'
    required: false
    default: 'public'
  git-user-name:
    description: 'Git user.name for the tagging commit'
    required: false
    default: 'github-actions[bot]'
  git-user-email:
    description: 'Git user.email for the tagging commit'
    required: false
    default: 'github-actions[bot]@users.noreply.github.com'
  dry-run:
    description: 'Do a dry run of npm publish'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'

    - name: Install
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: npm ci

    - name: Configure git
      shell: bash
      run: |
        git config user.name "${{ inputs.git-user-name }}"
        git config user.email "${{ inputs.git-user-email }}"

    - name: Bump version and tag (patch)
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: npm version patch -m "chore(release): %s [skip ci]"

    - name: Publish to npm
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        NODE_AUTH_TOKEN: ${{ env.NODE_AUTH_TOKEN }}
      run: |
        if [ "${{ inputs.dry-run }}" = "true" ]; then
          npm publish --access ${{ inputs.access }} --dry-run
        else
          npm publish --access ${{ inputs.access }}
        fi

    - name: Push commit and tags
      shell: bash
      run: |
        BRANCH="$(git rev-parse --abbrev-ref HEAD)"
        git push origin "HEAD:${BRANCH}" --follow-tags
