name: 'Publish NPM - patch'
description: 'Bump patch version and publish to npm'
inputs:
  git-user-name:
    description: 'Git user.name for the tagging commit'
    required: false
    default: 'github-actions[bot]'
  git-user-email:
    description: 'Git user.email for the tagging commit'
    required: false
    default: 'github-actions[bot]@users.noreply.github.com'

runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'

    - name: Install
      shell: bash
      run: npm ci

    - name: Configure git
      shell: bash
      run: |
        git config user.name "${{ inputs.git-user-name }}"
        git config user.email "${{ inputs.git-user-email }}"

    - name: Bump version
      shell: bash
      run: npm version patch

    - name: Publish to npm
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ env.NODE_AUTH_TOKEN }}
      run: |
        npm publish
